### ISSUE TITLE
Teensy 3.1 errors out with unhelpful error message (suggestion)

### ISSUE THREAD

**Issue by mnapolitano89** [MrYsLab/pymata-aio#23]
Teensy board throws the error "Initializing Arduino - Please wait... Cannot instantiate serial interface: /dev/tty.usbmodem958211", which is fixed by increasing arduino_wait - this isn't obvious to the end user as the needed step, suggesting that might be helpful :)

**Comment by MrYsLab** [comment]
@mnapolitano89 How long of a delay does it need? I will put that into the documentation.

**Comment by mnapolitano89** [comment]
changing to 5 worked for me

**Comment by MrYsLab** [comment]
Thanks. I will document this. I am coming out with version 2 in the next few weeks, that is based upon Python 3.5 and I will make sure this gets incorporated into the documentation. Thanks again for letting me know.

**Comment by mnapolitano89** [comment]
Thank you for writing this awesome bit of code! It's making my scientific life significantly easier

**Comment by MrYsLab** [comment]
@mnapolitano89 Wiki  example pages updated with a table of some typical arduino_wait times. Thanks for the kind words and great suggestion.
