### ISSUE TITLE
pin mode issues

### ISSUE THREAD

**Issue by soundanalogous** [MrYsLab/pymata-aio#37]
When adding pin modes not yet supported by Firmata I recommend either starting backwards from `0x7e` or submitting a proposal to have a pin mode reserved in Firmata. Otherwise you will find it difficult when you update to newer Firmata protocol versions. For example, you have diverged from the pin modes that are (loosely) documented in the protocol: https://github.com/MrYsLab/pymata-aio/blob/master/pymata_aio/constants.py#L34-L37

According to the [protocol](https://github.com/firmata/protocol/blob/master/protocol.md#control-messages-expansion) however:
```
0x09 = ENCODER
0x0a = SERIAL
0x0b = INPUT_PULLUP
```

While there is not a strict requirement to follow this (anyone can use Firmata however they want and distribute their own "StandardFirmata" variant), following this will make updating easier if you add features such as SERIAL and INPUT_PULLUP at some point in the future, especially since I have been adding new features such as SERIAL as [separate classes](https://github.com/firmata/arduino/blob/master/utility/SerialFirmata.cpp) to help manage complexity.

**Comment by MrYsLab** [comment]
Thanks.

I have just published a newer version of FirmataPlus to support [Xideco](https://github.com/MrYsLab/xideco/wiki) that is based on Standard Firmata 2.5.2.  The new pin modes, have been added to my existing modes, but they do deviate somewhat from the "standard" values of StandardFirmata. At some point, I will converge back to the standard values, but I need to understand all of the flavors of Arduino Firmata that now are included with the Firmata library. Once I get a handle on all the changes I will be updating pymata-aio.
