### ISSUE TITLE
FirmataPlus Arduino IDE Compilation Error

### ISSUE THREAD

**Issue by masteredward** [MrYsLab/pymata-aio#45]
Hello,

My Arduino IDE is reporting some errors, aborting the compilation. I'm using version 2:1.0.5 of Arduino IDE. Here is the error:

FirmataPlus.ino: In function ‘void setPinModeCallback(byte, int)’:
FirmataPlus.ino:339:20: error: ‘disableI2CPins’ was not declared in this scope
FirmataPlus.ino:347:77: error: ‘reportAnalogCallback’ was not declared in this scope
FirmataPlus.ino: In function ‘void sysexCallback(byte, byte, byte*)’:
FirmataPlus.ino:680:23: error: ‘enableI2CPins’ was not declared in this scope
FirmataPlus.ino:871:36: error: ‘printData’ was not declared in this scope

Can you give me some advice? Thanks!

**Comment by MrYsLab** [comment]
The version of the IDE that the code is tested against is 1.6.12 and can be downloaded here: https://www.arduino.cc/en/Main/Software

Please try using this version and let me know if you are still having issues or if this solves the problem.

**Comment by masteredward** [comment]
Problem solved! I was using the version distributed in Ubuntu Xenial Repo (1.0.5). Compiled only with warnings! Thanks!
