### ISSUE TITLE
Compatibility and Python 3.6

### ISSUE THREAD

**Issue by NervenCid** [MrYsLab/pymata-aio#49]
Hello:

I'm new using firmata protocol, and looking a first steps guide...

pyMata was installed well aparantely in Python 3.6... is recommendable to use it on Python 3.6?

This library is compatible with all arduino boards?

Thank you

**Comment by MrYsLab** [comment]
pymata-aio is compatible with both Python 3.5 and 3.6. The FirmataPlus library is know to support all of the boards with Atmel chips such as the Uno, Leonardo, Mega2560, Teensy and others.

**Comment by MrYsLab** [comment]
I am closing this since it was a question that was answered. If you have any other questions please feel free to ask.
