### ISSUE TITLE
How can I make a unit test for board connection?

### ISSUE THREAD

**Issue by JosephMart** [MrYsLab/pymata-aio#63]
How do you suggest that I create a unit test for validation a proper connection to an Arduino board?

**Comment by MrYsLab** [comment]
There are 2 possibilities to test for:
1. The board is not plugged.
2. The board is plugged in, but the incorrect sketch is loaded on Arduino.

Is this what you are looking for? 

```
import asyncio
from pymata_aio.pymata3 import PyMata3

def test_connection():
    try:
        board = PyMata3()
    # Board not plugged in - correct sketch or not
    except TypeError:
        assert False
    # incorrect sketch loaded
    except asyncio.futures.CancelledError:
        assert False
```

**Comment by JosephMart** [comment]
Yep this is what I wanted. Thanks!
