### ISSUE TITLE
Lots of output

### ISSUE THREAD

**Issue by bitcraft** [MrYsLab/pymata-aio#7]
First of all, thanks for your work with this project.  I've just begun to use it and I'm very hopeful to integrate it into my own projects.  One issue that I have with it is that it is very chatty and produces lots of output to STDOUT.  How about using the logging module so they can be suppressed?  I'm happy to contribute, too.  So if you'd like a RP for this or any other issues I raise let me know.

**Comment by MrYsLab** [comment]
I will add an option to log the output so it is not seen on the console.

**Comment by MrYsLab** [comment]
Adding logging with release 1.3
