### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by bitcraft** [MrYsLab/pymata-aio#8]
Are you planning on supporting the Windows OS?  Currently, I am unable to run this with windows.  The problem is here:
https://github.com/MrYsLab/pymata-aio/blob/master/pymata_aio/pymata_core.py#L1261

Windows doesn't implement SIGALRM, so this line fails.  It is just to handle keyboard breaks?  Could it be possible to make the control-c handling optional?

**Comment by MrYsLab** [comment]
Windows can't handle a sigalrm, so it will be removed in the next release.

**Comment by MrYsLab** [comment]
Fixed with release 1.3
